# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Fledi Ymerasi
tagline:          
url:              http://desaretiuss.github.io
paginate:         1
baseurl:          /
author:
  name:           Fledi Ymerasi
  url:            
  email:          flediymerasi@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/desaretiuss/desaretiuss.github.io.git
